 <?php
 
 /**
 * Implementation of hook_init().
 */
function wall_init() {
	// Load required js and css files.
	$path = drupal_get_path('module', 'wall');
	drupal_add_js($path . '/js/script.js');
}
 
/**
 * Implementation of hook_menu().
 */ 

 function wall_menu() {
  $items['wall/add/%'] = array(
	'page callback' => '_process_image',			
	'access callback' => TRUE,
	'page arguments' => array(1), 
	'file' => 'wall.admin.inc',	
  );
  return $items;
}

function wall_block_info() {
  $blocks = array();
  $blocks['add_wall_poster'] = array(
    'info' => t(''),    
    'status' => TRUE,     
  );
  return $blocks;
}


function wall_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  $block = array();
  switch ($delta) {
    case 'add_wall_poster':
      // Create your block content here
      //$block['subject'] = t('Add Wall Poster');
      $block['content'] = drupal_get_form('add_wall_poster_form');
      break;
  }
  return $block;
}

function add_wall_poster_form($form, &$form_submit){
	
	$form['title'] = array(
			'#type' => 'textfield',
			'#title' => t('Poster Title'),
			'#description' => t(''),
			'#attributes' => array('class' => array('addtitle')),
	);
	
	$form['link'] = array(
			'#type' => 'textfield',
			'#title' => t('Link'),
			'#description' => t(''),
			'#attributes' => array('class' => array('addlink')),
	);
	
	$form['embed_code'] = array(
			'#type' => 'textfield',
			'#title' => t('Image URL'),
			'#description' => t(''),
			'#attributes' => array('class' => array('addimage')),
	);
	
	
	
	$form['submit'] = array(
			'#type' => 'submit',
			'#ajax' => array(
			  'callback' => 'wall_submit_driven_callback',
			  'wrapper' => 'ADDIMAGE-OUTPUT',
			),
			'#value' => t('Next'),
			'#attributes' => array('class' => array('addbutton')),
	); 
	
	 $form['ADDIMAGE-OUTPUT'] = array(
		'#type' => 'markup',
		'#prefix' => '<div id="ADDIMAGE-OUTPUT" class="addimageoutput">',
		'#suffix' => '</div>',
		'#markup' => '',		
	 );


	return $form;
}

/**
 * Callback for submit_driven example.
 */
function wall_submit_driven_callback($form, $form_state) {
	
	$element = $form['ADDIMAGE-OUTPUT'];
	$element['#markup'] = $form['embed_code']['#value']. date('c');
	
	$file = wall_add_submit($form, $form_state);
	
	//Create poster node programatically
	$node = new stdClass();
	$node->type = 'poster';
	node_object_prepare($node);
	
	$node->title    							= $form['title']['#value'];
	$node->field_link							= $form['link']['#value'];
	$node->field_poster_image[LANGUAGE_NONE][0] = (array)$file; 	
	$node->language = LANGUAGE_NONE;
	node_save($node);
	
	return $element;
}


function wall_add_submit($form, &$form_state) {
  $embed_code = $form_state['values']['embed_code'];
  try {
    // Save the remote file
    $provider = media_internet_get_provider($embed_code);
    // Providers decide if they need to save locally or somewhere else.
    // This method returns a file object
    $file = $provider->save();
	return $file;
  }
  catch (Exception $e) {
    form_set_error('embed_code', $e->getMessage());
    return;
  }

  if (!$file->fid) {
    form_set_error('embed_code', t('The file %file could not be saved. An unknown error has occurred.', array('%file' => $embed_code)));
    return;
  }

 
}
